add usb features
Prevent crashing of settings when going into Connected Devices.

   E SystemServiceRegistry: No service published for: usb

followed by NPE:

   java.lang.RuntimeException: Unable to start activity
   ComponentInfo{com.android.settings/com.android.settings.Settings$ConnectedDeviceDashboardActivity}:
   java.lang.NullPointerException: Attempt to invoke virtual method
   'java.util.List android.hardware.usb.UsbManager.getPorts()'
   on a null object reference

Bug: 189904047
Test: check settings doesn't crash anymore
Signed-off-by: Pat Tjin <pattjin@google.com>
Change-Id: I1dd8df5cf70500b3dbb95009783dc2ba89e5ce13
(cherry picked from commit ac54e6697c3a12575305990f559972b4df9185ed)